# Generated by Django 4.0.3 on 2024-01-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_schedule_bus_alter_schedule_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
